### ISSUE TITLE
Improve client-side HTML sanitizing and BBCode parsing

### ISSUE THREAD

**Issue by sickboy** [SIXNetworks/withSIX.Web-Frontend#52]
- [x] Support `[url=xxxx]link[/url]` tags (not just `[url="xxxx]link[/url]`
- [x] Sanitize HTML for security purposes
- [x] Be more leniant with user errors (missing closing tags, etc) 
- [x] Support `[list][*]...[/list]` #53
- [x] Support `quote`, `size`, `color`, `s` and `center`. and `img` source optionally as attr.

**Comment by Sonsalt** [comment]
@sickboy please give me something to go with for testing

**Comment by sickboy** [comment]
@Sonsalt CBA mod or ACE3 mod links working in BI Forums Info section

**Comment by sickboy** [comment]
Added `[list][*]...[/list]` support
